/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import javax.swing.JOptionPane;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.util.Date;
import javax.swing.*;


/**
 *
 * @author Aakriti
 */
public class paymentslip extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public paymentslip() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_jobtitle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Employee ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 80, 131, 30);

        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(390, 72, 220, 40);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText("First Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(253, 158, 117, 36);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(253, 238, 110, 38);
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(390, 155, 220, 40);
        getContentPane().add(txt_lastname);
        txt_lastname.setBounds(390, 235, 220, 38);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setText("Date of Birth:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 320, 130, 33);
        getContentPane().add(txt_dob);
        txt_dob.setBounds(390, 310, 220, 39);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setText("Department:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(851, 79, 130, 30);
        getContentPane().add(txt_department);
        txt_department.setBounds(1011, 72, 210, 40);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setText("Job Title:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(857, 161, 110, 31);
        getContentPane().add(txt_jobtitle);
        txt_jobtitle.setBounds(1011, 154, 210, 40);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setText("Basic Salary:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(853, 238, 140, 38);

        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_salary);
        txt_salary.setBounds(1011, 235, 210, 38);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generate Slip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 422, 210, 60);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 520, 120, 50);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(870, 420, 130, 62);

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1060, 280, 830, 860);

        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1540, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_salaryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
            String val1 = txt_id.getText();
             String val2 = txt_firstname.getText();
            String lastname = txt_lastname.getText();
            String val3 = txt_dob.getText();
             String val4 = txt_department.getText();
              String val5 = txt_jobtitle.getText();

               String salary = txt_salary.getText();        
    PreparedStatement ps = null;
    ResultSet rs = null;
         /* try {
                  String salaryQuery = "SELECT salary FROM empregister WHERE id = ?";

               String salary = txt_salary.getText();*/
 

          try {
            String salaryQuery = "SELECT * FROM empregister WHERE id = ?";
    ps = db.connect().prepareStatement(salaryQuery);
    ps.setString(1, val1); // Set the employee ID
    rs = ps.executeQuery();


   float basicSalary = 0; // Initialize basicSalary

    if (rs.next()) {
        basicSalary = rs.getFloat("salary"); // Get basic salary from empregister table
    }
    rs.close();
    ps.close();  
              
            String deductionQuery = "SELECT * FROM deductions WHERE id = ?";
    ps = db.connect().prepareStatement(deductionQuery);
    ps.setString(1, val1); // Set the employee ID
    rs = ps.executeQuery();

    String deductionAmount = "0"; // Initialize deductionAmount
    if (rs.next()) {
        deductionAmount = rs.getString("deduction_amount"); // Adjust column name
    }
    rs.close();
    ps.close();

    // Fetch allowances from the database
    String allowanceQuery = "SELECT * FROM allowance WHERE id = ?";
    ps = db.connect().prepareStatement(allowanceQuery);
    ps.setString(1, val1); // Set the employee ID
    rs = ps.executeQuery();

    String overtime = "0", bonus = "0", otherAllowance = "0", totalAmount = "0"; // Initialize variables
    if (rs.next()) {
        overtime = rs.getString("Overtime"); // Adjust column name
        bonus = rs.getString("Bonus"); // Adjust column name
        otherAllowance = rs.getString("Other"); // Adjust column name
        totalAmount = rs.getString("TotalAmount");
    }
    rs.close();
    ps.close();
   
    // Calculate total payment
   // Calculate total payment
//float basicSalary = Float.parseFloat(salary); // Handle decimal input
float totalEarnings = Float.parseFloat(totalAmount); // Handle decimal input
float totalDeductions = Float.parseFloat(deductionAmount); // Handle decimal input
float netPay = basicSalary + totalEarnings - totalDeductions;

    /*String allowanceQuery = "SELECT * FROM empregister WHERE id = ?";
    ps = db.connect().prepareStatement(allowanceQuery);
    ps.setString(1, val1); // Set the employee ID
    rs = ps.executeQuery();
 rs.close();
 ps.close();*/

            // Create a Document object to generate PDF
            Document document = new Document();
      //String filePath = "C:\\Users\\ACER\\OneDrive\\Desktop\\Project PDF/Payment Slip.pdf";  
     // String filePath = "D:\\a/Payment Slip.pdf";

      String filePath = "C:\\Users\\ACER\\OneDrive\\Desktop\\Project PDF/Payment Slip.pdf";  

            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();

         Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
    Paragraph title = new Paragraph("Employee Payment Slip", titleFont);
    title.setAlignment(Element.ALIGN_CENTER);
    document.add(title);

    // Add a blank line
    document.add(new Paragraph(" "));


    // Add bill details in a structured format
    document.add(new Paragraph("PAY SLIP", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
document.add(new Paragraph(new Date().toString()));
document.add(new Paragraph("-------------------------------------------------------------------------------------------"));

// Employee Details
document.add(new Paragraph("EMPLOYEE DETAILS:", FontFactory.getFont(FontFactory.TIMES_BOLD, 14)));
document.add(new Paragraph("Name of Employee: " + val2 + " " + lastname, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("jobtitle: " + val5, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("Department: " + val4, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("-------------------------------------------------------------------------------------------"));

// Salary Details
document.add(new Paragraph("SALARY DETAILS:", FontFactory.getFont(FontFactory.TIMES_BOLD, 14)));
document.add(new Paragraph("Basic Salary: Rs. " + salary, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("Overtime: " + overtime + " Hours", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("Bonus: Rs. " + bonus, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("Other Allowances: Rs." + otherAllowance, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("-------------------------------------------------------------------------------------------"));

// Deduction Details
document.add(new Paragraph("DEDUCTION DETAILS:", FontFactory.getFont(FontFactory.TIMES_BOLD, 14)));

document.add(new Paragraph("Total Deductions: Rs." + deductionAmount, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("-------------------------------------------------------------------------------------------"));

// Total Payment Details
document.add(new Paragraph("TOTAL PAYMENT DETAILS:", FontFactory.getFont(FontFactory.TIMES_BOLD, 14)));
document.add(new Paragraph("Total Earnings: Rs. " + totalEarnings, FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("Net Pay: Rs. " + String.format("%.2f", netPay), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12)));
document.add(new Paragraph("-------------------------------------------------------------------------------------------"));



            // Close the document
            document.close();

            // Show success message
            JOptionPane.showMessageDialog(null, "PDF created successfully!");
        } catch (Exception ex) {
            // Handle any exceptions (e.g., file errors, iText issues)
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        // TODO add your handling code here:
         PreparedStatement ps = null;
    ResultSet rs = null;
    
        try {
        String query = "SELECT * FROM empregister  WHERE id = ?";
        ps = db.connect().prepareStatement(query);
        ps.setString(1, txt_id.getText());
        rs = ps.executeQuery();

        if (rs.next()) {
            txt_firstname.setText(rs.getString("firstname"));
            txt_lastname.setText(rs.getString("lastname"));
            txt_dob.setText(rs.getString("dateofbirth"));
            txt_salary.setText(rs.getString("salary"));
            txt_department.setText(rs.getString("department"));
            txt_jobtitle.setText(rs.getString("jobtitle"));
        } else {
            JOptionPane.showMessageDialog(null, "No record found");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error fetching employee details: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_txt_idKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         txt_id.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_salary.setText("");
        txt_department.setText("");
        txt_dob.setText("");
        txt_jobtitle.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new paymentslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_jobtitle;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_salary;
    // End of variables declaration//GEN-END:variables
}
