
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aakriti
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(filler1);
        filler1.setBounds(111, 123, 0, 0);

        jInternalFrame1.setMaximumSize(new java.awt.Dimension(15000, 1500));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Employee ID:");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 8, 140, 32);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(162, 6, 1010, 32);

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setToolTipText("");
        jLabel15.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel15);
        jLabel15.setBounds(-20, 0, 1340, 50);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(130, 50, 1240, 87);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(131, 6, 82, 24);

        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jTextField2);
        jTextField2.setBounds(174, 30, 239, 37);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setText("Employee ID:");
        jInternalFrame2.getContentPane().add(jLabel4);
        jLabel4.setBounds(33, 37, 135, 26);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setText("Address:");
        jInternalFrame2.getContentPane().add(jLabel5);
        jLabel5.setBounds(531, 36, 118, 29);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setText("Department:");
        jInternalFrame2.getContentPane().add(jLabel6);
        jLabel6.setBounds(531, 106, 117, 36);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setText("First Name:");
        jInternalFrame2.getContentPane().add(jLabel7);
        jLabel7.setBounds(33, 106, 128, 36);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel8.setText("Last Name:");
        jInternalFrame2.getContentPane().add(jLabel8);
        jLabel8.setBounds(33, 180, 128, 35);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setText("Gender:");
        jInternalFrame2.getContentPane().add(jLabel9);
        jLabel9.setBounds(33, 325, 115, 33);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel10.setText("Job Title:");
        jInternalFrame2.getContentPane().add(jLabel10);
        jLabel10.setBounds(531, 180, 117, 35);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel11.setText("Date Of Birth:");
        jInternalFrame2.getContentPane().add(jLabel11);
        jLabel11.setBounds(33, 254, 128, 36);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel12.setText("Contact:");
        jInternalFrame2.getContentPane().add(jLabel12);
        jLabel12.setBounds(33, 391, 102, 28);
        jInternalFrame2.getContentPane().add(jTextField3);
        jTextField3.setBounds(173, 103, 240, 38);
        jInternalFrame2.getContentPane().add(jTextField4);
        jTextField4.setBounds(173, 176, 240, 38);
        jInternalFrame2.getContentPane().add(jTextField5);
        jTextField5.setBounds(173, 251, 240, 39);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jTextField6);
        jTextField6.setBounds(670, 242, 251, 36);
        jInternalFrame2.getContentPane().add(jTextField7);
        jTextField7.setBounds(173, 385, 240, 36);
        jInternalFrame2.getContentPane().add(jTextField8);
        jTextField8.setBounds(670, 30, 251, 37);
        jInternalFrame2.getContentPane().add(jTextField9);
        jTextField9.setBounds(670, 104, 251, 36);
        jInternalFrame2.getContentPane().add(jTextField10);
        jTextField10.setBounds(670, 176, 251, 39);

        jRadioButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(182, 325, 88, 33);

        jRadioButton2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(309, 325, 98, 33);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel13.setText("Basic Salary:");
        jInternalFrame2.getContentPane().add(jLabel13);
        jLabel13.setBounds(531, 244, 117, 36);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton1);
        jButton1.setBounds(483, 343, 230, 43);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton2);
        jButton2.setBounds(770, 340, 200, 43);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton3);
        jButton3.setBounds(1020, 340, 110, 43);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(823, 430, 106, 43);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("History");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton5);
        jButton5.setBounds(513, 430, 176, 43);

        jLabel16.setBackground(new java.awt.Color(204, 204, 255));
        jLabel16.setOpaque(true);
        jInternalFrame2.getContentPane().add(jLabel16);
        jLabel16.setBounds(0, -10, 1220, 500);

        getContentPane().add(jInternalFrame2);
        jInternalFrame2.setBounds(140, 180, 1230, 525);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel3.setText("Personal Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(137, 142, 203, 31);

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-10, 0, 1700, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         PreparedStatement ps = null ;
         try{
         String updateempregisterQuery = "UPDATE empregister SET firstname = ?,lastname =?,dateofbirth = ?,gender =?,contact =?,address = ?,department=?,jobtitle=?,salary= ? WHERE id = ? ";
                        ps = db.connect().prepareStatement(updateempregisterQuery);
                        ps.setString(1, jTextField3.getText()); 
                        ps.setString(2, jTextField4.getText()); 
                        ps.setDate(3, java.sql.Date.valueOf(jTextField5.getText())); 
                        String gender;
                        if (jRadioButton1.isSelected()) {
                         gender = "1"; } 
                        else if (jRadioButton2.isSelected()) 
                        { gender = "0";}
                          else { 
                        gender = ""; 
                       } ps.setString(4, gender);
                         ps.setString(5, jTextField7.getText()); 
                        ps.setString(6, jTextField8.getText()); 
                        ps.setString(7, jTextField9.getText()); 
                        ps.setString(8, jTextField10.getText()); 
                        ps.setInt(9, Integer.parseInt(jTextField6.getText())); 
                        ps.setInt(10, Integer.parseInt(jTextField2.getText()));
                ps.executeUpdate();
             JOptionPane.showMessageDialog(null, " Updated successfully!");
         }
         catch (SQLException ex){
              JOptionPane.showMessageDialog(null, "SQL Error: " + ex.getMessage());
         }
         /**/

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        String query = "SELECT * FROM empregister  WHERE id = ?";
        ps = db.connect().prepareStatement(query);
        ps.setString(1, jTextField1.getText());
        rs = ps.executeQuery();

        if (rs.next()) {
            jTextField2.setText(rs.getString("id"));
            jTextField3.setText(rs.getString("firstname"));
            jTextField4.setText(rs.getString("lastname"));
            jTextField5.setText(rs.getString("dateofbirth"));
            jTextField8.setText(rs.getString("address"));
            jTextField10.setText(rs.getString("jobtitle"));
            jTextField7.setText(rs.getString("contact"));
             int gender = rs.getInt("gender");
        if (gender == 0) {
            jRadioButton2.setSelected(true);
        } else if (gender == 1) {
            jRadioButton1.setSelected(true);
        } 
            jTextField6.setText(rs.getString("salary"));
            jTextField9.setText(rs.getString("department"));
        } else {
            JOptionPane.showMessageDialog(null, "No record found");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error fetch TextField2ing employee details: " + ex.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error closing resources: " + ex.getMessage());
        } 
} 
        
        
        
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
          jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
          jRadioButton2.setSelected(true);
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                 PreparedStatement ps = null ;
                    int p= JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?", "Delete Record", JOptionPane.YES_NO_OPTION);
                    if (p==0){
         try{
                      String updateallowanceQuery = "DELETE FROM allowance WHERE id = ? ";
                        ps = db.connect().prepareStatement(updateallowanceQuery);
                        ps.setInt(1, Integer.parseInt(jTextField2.getText()));
                ps.executeUpdate();
                         String updatededQuery = "DELETE FROM deductions WHERE id = ? ";
                        ps = db.connect().prepareStatement(updatededQuery);
                        ps.setInt(1, Integer.parseInt(jTextField2.getText()));
                ps.executeUpdate();
                String salaryupdatededQuery = "DELETE FROM salary_records WHERE employee_id = ? ";
                        ps = db.connect().prepareStatement(salaryupdatededQuery);
                        ps.setInt(1, Integer.parseInt(jTextField2.getText()));
                ps.executeUpdate();
         String updateempregisterQuery = "DELETE FROM empregister WHERE id = ? ";
                        ps = db.connect().prepareStatement(updateempregisterQuery);
                        ps.setInt(1, Integer.parseInt(jTextField2.getText()));
                ps.executeUpdate();
             JOptionPane.showMessageDialog(null, " Deleted successfully!");
                     jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
         }
         catch (SQLException ex){
              JOptionPane.showMessageDialog(null, "SQL Error: " + ex.getMessage());
         }finally { 
                 if (ps != null) { 
                 try { ps.close(); } 
                 catch (SQLException e) 
                 {
                 e.printStackTrace(); 
                 } 
                 } 
                 }
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:                                          
    try {
        int selectedEmpId = Integer.parseInt(jTextField1.getText());  
        new History(selectedEmpId).setVisible(true);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Employee ID", "Error", JOptionPane.ERROR_MESSAGE);
    }


        //int selectedRow = jTable1.getSelectedRow();
    //if (selectedRow != -1) { // Ensure a row is selected
       // int empId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString()); // Get employee ID
       // new History(empId).setVisible(true); // Pass ID to History form
        //this.dispose(); // Close the search window
    //} else{
        //JOptionPane.showMessageDialog(null, "Please select an employee!");
    //}
        //new History().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
